version: "3"
services:
  set_scraping_influxdb:
    image: influxdb:1.7.0
    volumes:
      - ./influxdb/conf/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./influxdb/storage:/var/lib/influxdb
    ports:
      - 1112:8086
    container_name: set_scraping_influxdb

  set_scraping_grafana:
    image: grafana/grafana:5.3.2
    volumes:
      - ./grafana/conf/custom.ini:/etc/grafana/grafana.ini
      - ./grafana/storage:/var/lib/grafana
    ports:
      - 1111:3000
    container_name: set_scraping_grafana

